FROM node:20-alpine

WORKDIR /app

COPY package.json ./


# Ajout pour éviter les erreurs réseau
RUN npm config set fetch-retries 5 && \
    npm config set fetch-retry-mintimeout 20000 && \
    npm config set fetch-retry-maxtimeout 120000

RUN npm install

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev"]
